### ISSUE TITLE
Variables with same first 15 characters in name are translated to same symbols?

### ISSUE THREAD

**Issue by baxpick** [danielgaskell/scc#1]
Hello, I have noticed this, not sure if this in intended or can/should be fixed.
Not very important as variables perhaps should not have names longer then 15 chars anyway, but still:

This can be compiled:

uint16_t    var012345678901;
uint8_t     Var0123456789012;

This can not be compiled:

uint16_t    var012345678901;
uint8_t     var0123456789012;

**Comment by danielgaskell** [comment]
This is intended behavior inherited from FCC - when compiling natively, the 15-character limitation helps keep the compiler from running out of memory.

But I don't think this is currently documented, and it should be, so well spotted.
